version: '3'
services:
  redis:
    image: redis:latest
    container_name: cache
    expose:
      - "6379"
  app:
    build: ./
    volumes:
      - ./:/app
    ports:
      - "3001:3001"
    container_name: nodeAppa
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3001
      - REDIS_KEY=messages
    command:
      sh -c 'npm i && npm start'
